version: "3.3"
services:
  postgres:
    container_name: "db"
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db/postgresdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
