version: "3.3"
services:
  postgres:
    container_name: "db"
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/postgresdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
